// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mMV68etdeCljq82-ICltR2EcuQfetVk',
    appId: '1:570983632012:web:3480fba0d228ccb3da3fa9',
    messagingSenderId: '570983632012',
    projectId: 'sies-gst-app',
    authDomain: 'sies-gst-app.firebaseapp.com',
    storageBucket: 'sies-gst-app.appspot.com',
    measurementId: 'G-RM1LQ96R83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkemw83ua7BkYdCYEzzLv3A5zdDH8yWuM',
    appId: '1:570983632012:android:257ab1415b64c4beda3fa9',
    messagingSenderId: '570983632012',
    projectId: 'sies-gst-app',
    storageBucket: 'sies-gst-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACXPKlcmZaaEL1y1Hm6KWO0klcA4LZyxY',
    appId: '1:570983632012:ios:347ae98bf001be34da3fa9',
    messagingSenderId: '570983632012',
    projectId: 'sies-gst-app',
    storageBucket: 'sies-gst-app.appspot.com',
    iosBundleId: 'com.example.siesGstNotes',
  );
}
